import { Tile } from '../models/tile';

export const TILES: Tile[] = [
    // tslint:disable: max-line-length
    {name: 'Apple',     bat:  3, run: 10, pitch:  7, field: 8, number:  1, imgPath: '../../assets/images/specifics/Appl.png', info: 'Crisp fruit; varies in color.'},
    {name: 'Banana',    bat:  3, run: 10, pitch:  7, field: 8, number:  2, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  3, run: 10, pitch:  7, field: 8, number:  3, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  3, run:  9, pitch:  7, field: 8, number:  4, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  3, run:  9, pitch:  7, field: 8, number:  5, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  3, run:  9, pitch: 10, field: 8, number:  6, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  3, run:  9, pitch: 10, field: 8, number:  7, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit, golden fruit inside. '},
    {name: 'Grape',     bat:  4, run:  9, pitch: 10, field: 8, number:  8, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
    {name: 'Banana',    bat:  4, run:  9, pitch: 10, field: 5, number: 12, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  4, run:  9, pitch:  5, field: 5, number: 13, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  4, run:  9, pitch:  5, field: 5, number: 14, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  4, run:  8, pitch:  5, field: 5, number: 15, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  4, run:  8, pitch:  9, field: 4, number: 16, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  4, run:  8, pitch:  9, field: 4, number: 17, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit with golden fruit inside. '},
    {name: 'Grape',     bat:  4, run:  8, pitch:  9, field: 4, number: 18, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
    {name: 'Apple',     bat:  4, run:  8, pitch:  5, field: 4, number: 21, imgPath: '../../assets/images/specifics/Appl.png', info: 'Crisp fruit; varies in color.'},
    {name: 'Banana',    bat:  4, run:  8, pitch:  5, field: 4, number: 22, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  4, run:  7, pitch:  5, field: 4, number: 23, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  5, run:  7, pitch:  4, field: 4, number: 24, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  5, run:  7, pitch:  4, field: 5, number: 25, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  5, run:  7, pitch:  4, field: 5, number: 26, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  5, run:  7, pitch:  4, field: 9, number: 27, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit with  golden fruit inside. '},
    {name: 'Grape',     bat:  5, run:  7, pitch:  4, field: 9, number: 28, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
    {name: 'Banana',    bat:  5, run:  6, pitch:  4, field: 9, number: 32, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  6, run:  6, pitch:  4, field: 9, number: 33, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  6, run:  6, pitch:  4, field: 9, number: 34, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  6, run:  6, pitch:  4, field: 9, number: 35, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  6, run:  6, pitch:  4, field: 5, number: 36, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  6, run:  6, pitch:  4, field: 5, number: 37, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit with  golden fruit inside. '},
    {name: 'Grape',     bat:  6, run:  6, pitch:  5, field: 6, number: 38, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
    {name: 'Apple',     bat:  6, run:  6, pitch:  7, field: 6, number: 41, imgPath: '../../assets/images/specifics/Appl.png', info: 'Crisp fruit; varies in color.'},
    {name: 'Banana',    bat:  6, run:  6, pitch:  7, field: 6, number: 42, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  6, run:  6, pitch:  7, field: 6, number: 43, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  6, run:  6, pitch:  7, field: 6, number: 44, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  7, run:  6, pitch:  7, field: 6, number: 45, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  7, run:  6, pitch:  7, field: 7, number: 46, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  7, run:  6, pitch:  7, field: 7, number: 47, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit with  golden fruit inside. '},
    {name: 'Grape',     bat:  7, run:  6, pitch:  7, field: 7, number: 48, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
    {name: 'Banana',    bat:  7, run:  6, pitch:  5, field: 7, number: 52, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  7, run:  6, pitch:  3, field: 7, number: 53, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  7, run:  6, pitch:  3, field: 7, number: 54, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  7, run:  6, pitch:  3, field: 7, number: 55, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  7, run:  5, pitch:  3, field: 7, number: 56, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  7, run:  5, pitch:  3, field: 7, number: 57, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit with  golden fruit inside. '},
    {name: 'Grape',     bat:  7, run:  5, pitch:  3, field: 7, number: 58, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
    {name: 'Apple',     bat:  7, run:  5, pitch:  3, field: 3, number: 61, imgPath: '../../assets/images/specifics/Appl.png', info: 'Crisp fruit; varies in color.'},
    {name: 'Banana',    bat:  7, run:  5, pitch:  3, field: 3, number: 62, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  8, run:  5, pitch:  3, field: 3, number: 63, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  8, run:  5, pitch:  3, field: 3, number: 64, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  8, run:  4, pitch:  3, field: 3, number: 65, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  8, run:  4, pitch:  3, field: 3, number: 66, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  8, run:  4, pitch:  3, field: 3, number: 67, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit with  golden fruit inside. '},
    {name: 'Grape',     bat:  8, run:  4, pitch:  5, field: 5, number: 68, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
    {name: 'Banana',    bat:  8, run:  4, pitch:  5, field: 5, number: 72, imgPath: '../../assets/images/specifics/Bana.png', info: 'Soft, yellow, and long.'},
    {name: 'Orange',    bat:  8, run:  4, pitch:  5, field: 5, number: 73, imgPath: '../../assets/images/specifics/Oran.png', info: 'Orange ball with tart fruit inside tough skin.'},
    {name: 'Peach',     bat:  8, run:  3, pitch:  5, field: 8, number: 74, imgPath: '../../assets/images/specifics/Peac.png', info: 'Soft sunshine colored fruit. Sour and sweet.'},
    {name: 'Lime',      bat:  9, run:  3, pitch:  5, field: 8, number: 75, imgPath: '../../assets/images/specifics/Lime.png', info: 'Sour, green, and fresh citrus fruit.'},
    {name: 'Mango',     bat:  9, run:  2, pitch:  5, field: 8, number: 76, imgPath: '../../assets/images/specifics/Mang.png', info: 'Sweet orange fruit.'},
    {name: 'Lemon',     bat:  9, run:  2, pitch:  5, field: 8, number: 77, imgPath: '../../assets/images/specifics/Lemo.png', info: 'Large fruit with  golden fruit inside. '},
    {name: 'Grape',     bat: 10, run:  2, pitch:  5, field: 8, number: 78, imgPath: '../../assets/images/specifics/Grap.png', info: 'Tiny, soft, and comes in many varieties.'},
];
